# Generated by Django 4.2.28 on 2026-04-28 16:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Velo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cadre', models.CharField(max_length=50, unique=True, verbose_name='Numéro de cadre')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('type', models.CharField(choices=[('VTT', 'VTT'), ('Electrique', 'Électrique'), ('Ville', 'Ville')], max_length=20, verbose_name='Type')),
                ('prix_heure', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix/heure (€)')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Vélo',
                'verbose_name_plural': 'Vélos',
                'ordering': ['modele'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Durée')),
                ('duree_unite', models.CharField(choices=[('heures', 'Heures'), ('jours', 'Jours')], default='heures', max_length=10, verbose_name='Unité de durée')),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix total (€)')),
                ('date_location', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de location')),
                ('date_retour', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour prévue')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=15, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.client', verbose_name='Client')),
                ('velo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.velo', verbose_name='Vélo')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-date_location'],
            },
        ),
    ]
