# Generated by Django 4.2.28 on 2026-05-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='duree',
            field=models.PositiveIntegerField(verbose_name='Durée'),
        ),
    ]
