# Generated by Django 4.2.28 on 2026-05-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='duree',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Durée'),
        ),
    ]
