# Generated by Django 4.2.28 on 2026-05-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='duree_unite',
            field=models.CharField(choices=[('heures', 'Heures'), ('jours', 'Jours (8h)')], default='heures', max_length=10, verbose_name='Unité de durée'),
        ),
    ]
